run:
  issues-exit-code: 1
  
linter-settings:
  lll:
    line-length: 200

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - golint
    - goconst
    - goimports
    - varcheck
    - deadcode
    - misspell

issues:
  exclude-use-default: false