Unauthorized = "Unauthorized"
coupon_unauthorized = "Please Login"
coupon_redeemed = "You are already redeemed"
coupon_point_incorrect = "The number of points must be divisible by 5"
coupon_cannot_redeemed = "Cannot redeem coupon"
coupon_point_notenough = "There are not enough points balance"
coupon_out_of_stock = "All coupons have been received. Cannot receive this coupon anymore."
me_point_label = "Point will be expired 31 Dec {{.Year}}: {{.Point}}"
order_timeout = "Order has expired"
boots_flash_sales_exceed = "You order reach limit QTY per item"
pls_select_shipping_method = "Please select a shipping method."
pls_login_before_starting_purchase =  "Please login before starting purchase."
pls_update_app =  "Please update your app to the latest version"
email_invalid =  "Invalid email"
bulk_sale_error_message = "Sorry you are over limit . If you wish to purchase more products, please contact Boots store near you."
hybrid_store_error_message = "Some product in your basket is insufficient stock. Please revise your order list before proceed the payment."