Unauthorized = "กรุณาลงทะเบียนเข้าระบบ"
coupon_unauthorized = "กรุณาลงชื่อเข้าใช้"
coupon_redeemed = "รับสิทธ์แล้ว"
coupon_cannot_redeemed = "ไม่สามารถรับสิทธ์ได้"
coupon_point_incorrect = "จำนวนคะแนนต้องหารด้วย 5 ลงตัว"
coupon_point_notenough = "จำนวนคะแนนคงเหลือไม่เพียงพอ"
coupon_out_of_stock = "ได้รับคูปองครบแล้ว ไม่สามารถรับคูปองนี้ได้อีก"
me_point_label = "หมดอายุ 31 ธ.ค. {{.Year}}: {{.Point}} คะแนน"
invalid_order = "รายการคำสั่งซื้อนี้ได้ทำรายการเสร็จสิ้นแล้ว ท่านสามารถดูรายการได้ที่ เมนูบู๊ทส์การ์ด -> รายการคำสั่งซื้อ"
order_timeout = "รายการคำสั่งซื้อนี้หมดอายุกรุณาสั่งซื้อใหม่อีกครั้ง"
boots_flash_sales_exceed = "ท่านซื้อสินค้าครบตามจำนวนที่กำหนดแล้ว"
pls_select_shipping_method = "กรุณาเลือกวิธีการจัดส่ง"
pls_login_before_starting_purchase =  "กรุณาเข้าสู่ระบบ"
pls_update_app =  "กรุณาอัพเดทแอพพลิเคชั่นเป็นเวอร์ชั่นล่าสุด"
email_invalid =  "Email ไม่ถูกต้อง"
bulk_sale_error_message = "ไม่สามารถเพิ่มจำนวนสินค้าได้ เนื่องจากคุณเพิ่มสินค้าถึงจำนวนที่กำหนดแล้ว หากต้องการซื้อสินค้าจำนวนมาก กรุณาติดต่อที่บู๊ทส์ สาขาใกล้บ้านคุณ"
hybrid_store_error_message = "สินค้าในตะกร้าไม่เพียงพอ กรุณาแก้ไขตะกร้าสินค้าของท่าน ก่อนดำเนินการชำระเงิน"