RELEASE: false
PRODUCTION: false
SERVER_PORT: :8000

DATA_BASE_URL: cluster0.62mukj5.mongodb.net
DATA_BASE_PORT: 27017
DATA_BASE_NAME: auditor
DATA_BASE_ROOT: true
DATA_BASE_USERNAME: root
DATA_BASE_PASSWORD: yXq0ptCs1BkDkbqW

REDIS_ON: false
REDIS_HOST: 35.154.45.2:6379
REDIS_PASSWORD: WVRKME1tTkhlREZqZHowOQ

