RELEASE: false
PRODUCTION: false
SERVER_PORT: :8000
DATA_BASE_URL: cluster0.62mukj5.mongodb.net
DATA_BASE_PORT: 27017
DATA_BASE_NAME: auditor
DATA_BASE_ROOT: true
DATA_BASE_USERNAME: root
DATA_BASE_PASSWORD: yXq0ptCs1BkDkbqW
JWT_SECRET: auditor_jwt_secret
PARTNER_JWT_SECRET: partner_jwt_secret
REDIS_ON: false
REDIS_HOST: 35.154.45.2:6379
REDIS_PASSWORD: WVRKME1tTkhlREZqZHowOQ
SWAGGER_HOST: localhost:8000
SWAGGER_BASE_PATH: /api/v1
OTP_EXPIRATION_TIME: 600
ORDER_TIME_OUT: 30
PRODUCT_REVIEW_NOTIFICATION: 2
