invalid_parameters:
  code: 1000000
  message: "Invalid parameters"

invalid_id:
  code: 1000001
  message: "ID is invalid"

data_notfound:
  code: 1000002
  message: "Data Not Found"

invalid_login_type:
  code: 2000001
  message: "Invalid login type"

invalid_email:
  code: 2000002
  message: "Email address is not valid"

invalid_password:
  code: 2000003
  message: "Password does not match"

invalid_facebook_token:
  code: 2000004
  message: "Invalid Facebook token"

invalid_google_token:
  code: 2000005
  message: "Invalid Google token"

boots_service_unavailable:
  code: 3000001
  message: "Service unavailable"

member_not_found:
  code: 3000002
  message: "ไม่พบข้อมูลสมาชิกในระบบ กรุณาสมัครสมาชิก"

member_already_existing:
  code: 3000003
  message: "มีสมาชิกอยู่ในระบบแล้ว ท่านสามารถเข้าสู่ระบบได้ทันที หรือติดต่อ Call center"

register_boots:
  code: 3000004
  message: "ไม่พบข้อมูลในระบบ กรุณาติดต่อ Call center"

invalid_citizen:
  code: 3000005
  message: "หมายเลขบัตรประชาชนไม่ถูกต้อง"

boots_flash_sales_exceed:
  code: 3000006
  message: "ขออภัย สินค้ามีจำนวนไม่เพียงพอ"